---
image: python:3.6

include:
  project: infra/gitlab
  ref: master
  file: templates/python.ci.yml

test:
  stage: test
  script:
    - pip install .[dev]
    - python -m unittest djangoldp.tests.runner
  except:
    - master
    - tags
  tags:
    - test

crypto-test:
  stage: test
  script:
    - pip install .[crypto]
    - python -m unittest djangoldp_crypto.tests.runner
  except:
    - master
    - tags
  tags:
    - test

publish:
  extends: .publish_pypi


