---
version: '3'

services:

  server:
    image: python:3.6
    working_dir: /app
    environment:
      SETTINGS: |
        dependencies:
           - git+https://git.startinblox.com/djangoldp-packages/djangoldp-account.git@beta
           - djangoldp_circle
           - djangoldp_dashboard
           - djangoldp_conversation
           - djangoldp_notification==1.0.3
           - djangoldp_profile
           - djangoldp_project
           - djangoldp_skill
           - djangoldp_uploader
           - djangoldp_resource
           - djangoldp_event
           - djangoldp_polls
        ldppackages:
           - djangoldp_account
           - djangoldp_circle
           - djangoldp_dashboard
           - djangoldp_conversation
           - djangoldp_notification
           - djangoldp_profile
           - djangoldp_project
           - djangoldp_skill
           - djangoldp_uploader
           - djangoldp_resource
           - djangoldp_event
           - djangoldp_polls
        server:
          DEBUG: true
          ALLOWED_HOSTS: ['*']
          SECRET_KEY: '+t8(zmi)uf2&gzoq22qqtc+qn^un8eizfmyqq-vuyma_)ghdz3'
          DATABASES:
            default:
              ENGINE: django.db.backends.sqlite3
              NAME: db.sqlite3
          LDP_RDF_CONTEXT: https://cdn.happy-dev.fr/owl/hdcontext.jsonld
          ROOT_URLCONF: server.urls
          STATIC_ROOT: static
          MEDIA_ROOT: media
          JABBER_DEFAULT_HOST: 'localhost'
    command: >
      bash -c "
        pip install git+https://git.startinblox.com/djangoldp-packages/djangoldp.git@beta &&
        djangoldp initserver myserver &&
        echo \"$$SETTINGS\" > /app/myserver/settings.yml &&
        cd /app/myserver &&
        djangoldp install &&
        djangoldp configure
        python manage.py creatersakey &&
        djangoldp runserver
      "
    ports:
      - 127.0.0.1:8000:8000

  client:
    image: node
    working_dir: /app
    environment:
      CONFIG: |
        {
           "xmpp": "https://jabber.happy-dev.fr/http-bind/",
           "authority": "http://localhost:8000/",
           "clientName": "Digital Platform Observatory",
           "clientLogo": "https://cdn.happy-dev.fr/logos/digitalplatformobvervatory.png",
           "clientLogoHeight": "60px",
           "authorityName": "digital-platform-obvervatory",
           "publicDirectory": true,
           "endpoints":{
             "get":{
                "circles":"http://localhost:8000/circles/",
                "groups":"http://localhost:8000/groups/",
                "users":"http://localhost:8000/users/",
                "dashboards": "http://localhost:8000/dashboards/",
                "skills": "https://api.community.hubl.world/sources/skills/",
                "uploads":"http://localhost:8000/upload/",
                "events":"http://localhost:8000/events/",
                "typeevents":"http://localhost:8000/typeevents/",
                "resources":"http://localhost:8000/resources/",
                "resourceskeywords":"http://localhost:8000/keywords/",
                "resourcestypes":"http://localhost:8000/types/",
                "polls":"http://localhost:8000/polls/",
                "pollRangeBase": "http://localhost:8000/",
                "uploadDir":"http://localhost:8000/upload/"
             },
             "post":{
                "circles":"http://localhost:8000/circles/",
                "groups":"http://localhost:8000/groups/",
                "users":"http://localhost:8000/users/",
                "skills": "https://api.community.hubl.world/sources/skills/",
                "uploads":"http://localhost:8000/upload/",
                "events":"http://localhost:8000/events/",
                "typeevents":"http://localhost:8000/typeevents/",
                "resources":"http://localhost:8000/resources/",
                "resourceskeywords":"http://localhost:8000/keywords/",
                "resourcestypes":"http://localhost:8000/types/",
                "polls":"http://localhost:8000/polls/",
                "pollRangeBase": "http://localhost:8000/",
                "uploadDir":"http://localhost:8000/upload/"
             }
          }
        }
    command: >
      bash -c "
        git clone https://git.startinblox.com/applications/hubl.git /app &&
        npm install --only=production &&
        echo \"$$CONFIG\" > /app/config.json &&
        npm run build &&
        npm run serve
      "
    ports:
      - 127.0.0.1:3000:3000
