
dependencies:
  - git+https://git.startinblox.com/djangoldp-packages/djangoldp-account.git

ldppackages:

server:
  # App specific settings
  # Django required settings
  ALLOWED_HOSTS:
    - '*'
  SECRET_KEY: "{{secret_key}}"
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3
  STATIC_ROOT: static
  MEDIA_ROOT: media
  LDP_RDF_CONTEXT: https://cdn.happy-dev.fr/owl/hdcontext.jsonld
  PROSODY_HTTP_URL:
  JABBER_DEFAULT_HOST:
  ACCOUNT_ACTIVATION_DAYS: 10
