# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-06 06:42
from __future__ import unicode_literals

from django.db import migrations
import djangoldp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldpsource',
            name='container',
        ),
        migrations.AddField(
            model_name='ldpsource',
            name='urlid',
            field=djangoldp.fields.LDPUrlField(null=True, unique=True),
        ),
    ]
