# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='LDNotification',
        ),
    ]
